name: Build and Publish Docker Image

# Define when the workflow should run
on:
  # This workflow is triggered when the 'Detect Changes and Update Commit Hash' workflow completes successfully
  workflow_run:
    workflows: ["Detect Changes and Update Commit Hash"]
    types:
      - completed

# Define the jobs to be executed in this workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Specify the OS for the runner
    permissions:
      contents: read  # Grant read permissions to the repository content
      packages: write # Allow writing to the GitHub package registry
    steps:
    # Step 1: Check out the repository containing the workflow file
    - name: Checkout the workflow repository
      uses: actions/checkout@v4

    # Step 2: Clone the target repository and get the latest commit hash
    - name: Clone target repository
      run: |
        # Clone the target repository to the runner
        git clone https://github.com/${{ vars.REPO_PROFILE }}/${{ vars.REPO_NAME }}.git
        cd ${{ vars.REPO_NAME }}
        # Get the latest commit hash of the target repository
        latest_commit=$(git rev-parse HEAD)
        # Save the commit hash as an environment variable
        echo "LATEST_COMMIT=${latest_commit}" >> $GITHUB_ENV

    # Step 3: Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 4: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io  # Specify GitHub Container Registry as the target registry
        username: ${{ github.actor }}  # Use the GitHub actor as the username
        password: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}  # Use the Docker Hub username stored in secrets
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Use the Docker Hub access token stored in secrets

    - name: Build and push Docker image
      run: |
        set -x  # Enable debug mode to print commands as they are executed
        cd "${{ vars.REPO_NAME }}"  # Navigate to the cloned repository
        
        # Clean up variable values
        REPO_DOCKER=$(echo "${{ vars.REPO_NAME }}-docker" | tr -d '\r\n\t ' | tr '[:upper:]' '[:lower:]')
        LOWERCASE_REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr -d '\r\n\t ' | tr '[:upper:]' '[:lower:]')
        DOCKER_HUB_USERNAME=$(echo "${{ vars.DOCKER_HUB_USERNAME }}" | tr -d '\r\n\t ')
        
        # Debug output
        echo "REPO_DOCKER: ${REPO_DOCKER}"
        echo "LOWERCASE_REPO_OWNER: ${LOWERCASE_REPO_OWNER}"
        echo "DOCKER_HUB_USERNAME: ${DOCKER_HUB_USERNAME}"
        
        # Construct image tags
        GITHUB_CR_TAG="ghcr.io/${LOWERCASE_REPO_OWNER}/${REPO_DOCKER}:latest"
        DOCKER_HUB_TAG="${DOCKER_HUB_USERNAME}/${REPO_DOCKER}:latest"
        
        echo "GitHub CR tag: ${GITHUB_CR_TAG}"
        echo "Docker Hub tag: ${DOCKER_HUB_TAG}"
        
        # Build the Docker image
        docker build -t "${GITHUB_CR_TAG}" . -f Dockerfile
        
        # Tag for Docker Hub
        docker tag "${GITHUB_CR_TAG}" "${DOCKER_HUB_TAG}"
        
        # Push to GitHub Container Registry
        docker push "${GITHUB_CR_TAG}"
        
        # Push to Docker Hub
        docker push "${DOCKER_HUB_TAG}"

    # Step 7: Clean up the workspace
    - name: Clean up
      run: |
        rm -rf ${{ vars.REPO_NAME }}  # Remove the cloned repository to clean up the workspace